displayName=Wacky Sire
author=itscadle
description=Cosmetic flailing inflatable tube men in place of Abyssal Sire tentacles
tags=sire,abyssal,tentacle,cosmetic,tube,inflatable
plugins=com.wackysire.WackySirePlugin
version=0.1.2
build=standard
